
build:
  version: 1.0

accounts:
  message: "Welcome to Accounts app of Production"
  contactDetails:
    name: Prod Profile
    email: johny@example.com
  onCallSupport:
   - 955-955-955
   - 088-088-088



