 
build:
  version: 1.0

cards:
  message: "Welcome to Cards app with PRODuction Profile"
  contactDetails:
    name: Prod Profile
    email: prod@example.com
  onCallSupport:
   - 555-555-555
   - 888-888-888

