
server:
  port: 8071


spring:
  application:
    name: "configserver"
  profiles:
    #active: native # to load from classpath and also from file system
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config" # for loading profiles from classpath
          #search-locations: "file:///C://config" # for loading profiles from files system
        git:
          uri: https://github.com/sayemx/config-rep.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

encrypt:
  key: "jbsjdbsjdSjbsdj232jbjbajb"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      applications: ${spring.application.name}        
        
        
        